"""empty message

Revision ID: bd9e5a7609d4
Revises: a9c2d25c6949
Create Date: 2025-02-04 02:57:53.764471

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd9e5a7609d4'
down_revision = 'a9c2d25c6949'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorite',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('people_id', sa.Integer(), nullable=True),
    sa.Column('planet_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['people_id'], ['people.id'], ),
    sa.ForeignKeyConstraint(['planet_id'], ['planet.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('fav_People')
    op.drop_table('fav_Planets')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fav_Planets',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"fav_Planets_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('planet_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['planet_id'], ['planet.id'], name='fav_Planets_planet_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='fav_Planets_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='fav_Planets_pkey'),
    sa.UniqueConstraint('description', name='fav_Planets_description_key'),
    sa.UniqueConstraint('name', name='fav_Planets_name_key')
    )
    op.create_table('fav_People',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"fav_People_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('people_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['people_id'], ['people.id'], name='fav_People_people_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='fav_People_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='fav_People_pkey'),
    sa.UniqueConstraint('description', name='fav_People_description_key'),
    sa.UniqueConstraint('name', name='fav_People_name_key')
    )
    op.drop_table('favorite')
    # ### end Alembic commands ###
